# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "quay.io/pypa/manylinux1_x86_64:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
# You will often need this when you (or any of your dependencies) depends on C code.
before_script:
 - yum install xz
 - cd /usr/src
 - curl -o Python-3.7.7.tar.xz https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tar.xz
 - unxz Python-3.7.7.tar.xz
 - tar -xvf Python-3.7.7.tar
 - cd Python-3.7.7
 - yum install gcc
 - yum install openssl-devel
 - ./configure --prefix=/opt/python3
 - make altinstall
 - ln -s /opt/python3/bin/python3.7 /usr/bin/python3.7
 - python3.7 --version
 - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
 - python3.7 get-pip.py
 - pip3 install maturin
 - PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip
 - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP
 - unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
 - unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
 - rm -f $PROTOC_ZIP

# Use cargo to test the project
#test:cargo:
#  script:
#    - rustc --version && cargo --version  # Print version info for debugging
#    - cargo test --workspace --verbose

build:
 script:
  - maturin build --release
 artifacts:
  paths:
   - "*/target/wheels/*.whl"