[package]
name = "rust-arenaclient"
version = "0.1.2"
authors = ["Daniel <danielvanschoor1997@gmail.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_ac"
crate-type = ["cdylib"]

[[bin]]
name = "rust_ac_bin"
path = "src/main.rs"

[dependencies]
sc2-proto = { git = "https://github.com/UltraMachine/sc2-proto-rs.git" }
protobuf = { version = "*", features = ["with-bytes"] }
log = "0.4"
shellexpand = "1.0"
regex = "1.1.0"
portpicker  = { git = "https://github.com/danielvschoor/portpicker-rs" }
tempfile = "3"
crossbeam = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "*"
pretty_env_logger ="0.4.0"

[dependencies.websocket]
version = "0.24.0"
default-features = false
features = ["sync"]

[dependencies.pyo3]
version = "0.11.0"
features = ["extension-module"]

#[features]
#extension-module = ["pyo3/extension-module"]
#default = ["extension-module"]


[profile.release]
opt-level = 3
debug=false
panic="abort"
lto = "fat"
codegen-units = 1

