name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    - name: Build lib
      run: cargo build --lib --verbose      
    - name: Build bin
      run: cargo build --bin rust_ac_bin --no-default-features --verbose
    - name: Run tests
      run: cargo test --verbose --no-default-features
  
  maturin_build:
    needs: [build]
    runs-on: ubuntu-latest
    container: 
      image: konstin2/maturin:master
      volumes: 
        - ./:/io
    steps:
    - uses: actions/checkout@v2
    - name: maturin-build
      run: |
        rustup default stable
        maturin build --release
    - uses: actions/upload-artifact@v2
      name: upload-wheel
      with:
        name: wheel-many-linux
        path: target/wheels
