name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8] 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    - name: Build lib
      run: cargo build --lib --verbose      
    - name: Build bin
      run: cargo build --bin rust_ac_bin --no-default-features --verbose
    - name: Run tests
      run: cargo test --verbose --no-default-features --lib
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin
        pip install rust_ac/requirements.txt
    - name: Maturin build
      run: |
        maturin build
