name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build lib
      run: cargo build --lib --verbose
    - name: Build bin
      run: cargo build --bin rust_ac_bin --no-default-features --verbose
    - name: Run tests
      run: cargo test --verbose --no-default-features
